Public WITH SHARING class TESTINGCOPADO_AccountCreation 
{
    // Public Account createAccount(String name)
    // { 
    
    //     Account a= new Account();
        
    //     a.Name = name;
        
    //     insert a;
        
    //     // testing this
    //     return a;
    // } 
    
    //  Public Account createCopadoAccount(String name)
    // { 
    
    //     Account a= new Account();
        
    //     a.Name = name + '_COPADO';
        
    //     insert a;
        
    //     // testing this
    //     return a;
    // } 
}